[2015-03-09 18:59:05] production.ERROR: exception 'InvalidArgumentException' with message 'View [welcome] not found.' in /home/simeon/dev/sbalo.bg/storage/framework/compiled.php:12898
Stack trace:
#0 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(12871): Illuminate\View\FileViewFinder->findInPaths('welcome', Array)
#1 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(12996): Illuminate\View\FileViewFinder->find('welcome')
#2 /home/simeon/dev/sbalo.bg/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(563): Illuminate\View\Factory->make('welcome', Array, Array)
#3 /home/simeon/dev/sbalo.bg/app/Http/Controllers/WelcomeController.php(33): view('welcome')
#4 [internal function]: App\Http\Controllers\WelcomeController->index()
#5 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(8287): call_user_func_array(Array, Array)
#6 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(8354): Illuminate\Routing\Controller->callAction('index', Array)
#7 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(8333): Illuminate\Routing\ControllerDispatcher->call(Object(App\Http\Controllers\WelcomeController), Object(Illuminate\Routing\Route), 'index')
#8 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#9 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(8952): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#10 /home/simeon/dev/sbalo.bg/app/Http/Middleware/RedirectIfAuthenticated.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#11 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(8944): App\Http\Middleware\RedirectIfAuthenticated->handle(Object(Illuminate\Http\Request), Object(Closure))
#12 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#13 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(8935): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#14 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(8334): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#15 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(8320): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(App\Http\Controllers\WelcomeController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'index')
#16 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(7317): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\Http\Contro...', 'index')
#17 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(7288): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#18 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(6954): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#19 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#20 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(8952): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#21 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(8935): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#23 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(6955): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#24 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(6944): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#25 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(6929): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#26 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(1935): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#27 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#28 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(8952): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#29 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(2438): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 /home/simeon/dev/sbalo.bg/app/Http/Middleware/VerifyCsrfToken.php(17): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(8944): App\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(12083): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(8944): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(10785): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(8944): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#36 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(11789): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(8944): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(11738): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(8944): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(2478): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(8944): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(8935): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#44 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(1891): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#45 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(1880): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#46 /home/simeon/dev/sbalo.bg/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#47 {main}  
[2015-03-09 19:01:42] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '('' in /home/simeon/dev/sbalo.bg/app/Http/Controllers/HomeController.php:11
Stack trace:
#0 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(1738): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}  
[2015-03-09 19:01:43] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '('' in /home/simeon/dev/sbalo.bg/app/Http/Controllers/HomeController.php:11
Stack trace:
#0 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(1738): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}  
[2015-03-09 19:01:53] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '('' in /home/simeon/dev/sbalo.bg/app/Http/Controllers/HomeController.php:11
Stack trace:
#0 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(1738): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}  
[2015-03-09 19:01:53] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '('' in /home/simeon/dev/sbalo.bg/app/Http/Controllers/HomeController.php:11
Stack trace:
#0 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(1738): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}  
[2015-03-09 19:01:53] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '('' in /home/simeon/dev/sbalo.bg/app/Http/Controllers/HomeController.php:11
Stack trace:
#0 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(1738): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}  
[2015-03-09 19:01:54] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '('' in /home/simeon/dev/sbalo.bg/app/Http/Controllers/HomeController.php:11
Stack trace:
#0 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(1738): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}  
[2015-03-09 19:01:54] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '('' in /home/simeon/dev/sbalo.bg/app/Http/Controllers/HomeController.php:11
Stack trace:
#0 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(1738): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}  
[2015-03-09 19:02:00] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '('' in /home/simeon/dev/sbalo.bg/app/Http/Controllers/HomeController.php:11
Stack trace:
#0 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(1738): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}  
[2015-03-09 19:02:29] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '('' in /home/simeon/dev/sbalo.bg/app/Http/Controllers/HomeController.php:11
Stack trace:
#0 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(1738): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}  
[2015-03-09 19:02:29] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '('' in /home/simeon/dev/sbalo.bg/app/Http/Controllers/HomeController.php:11
Stack trace:
#0 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(1738): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}  
[2015-03-09 19:02:38] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Http\Controllers\View' not found' in /home/simeon/dev/sbalo.bg/app/Http/Controllers/HomeController.php:11
Stack trace:
#0 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(1738): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}  
[2015-03-09 19:02:38] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Http\Controllers\View' not found' in /home/simeon/dev/sbalo.bg/app/Http/Controllers/HomeController.php:11
Stack trace:
#0 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(1738): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}  
[2015-03-09 19:02:42] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Http\Controllers\View' not found' in /home/simeon/dev/sbalo.bg/app/Http/Controllers/HomeController.php:11
Stack trace:
#0 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(1738): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}  
[2015-03-09 19:02:42] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Http\Controllers\View' not found' in /home/simeon/dev/sbalo.bg/app/Http/Controllers/HomeController.php:11
Stack trace:
#0 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(1738): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}  
[2015-03-09 19:02:43] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Http\Controllers\View' not found' in /home/simeon/dev/sbalo.bg/app/Http/Controllers/HomeController.php:11
Stack trace:
#0 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(1738): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}  
[2015-03-09 19:02:43] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Http\Controllers\View' not found' in /home/simeon/dev/sbalo.bg/app/Http/Controllers/HomeController.php:11
Stack trace:
#0 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(1738): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}  
[2015-03-09 19:02:43] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Http\Controllers\View' not found' in /home/simeon/dev/sbalo.bg/app/Http/Controllers/HomeController.php:11
Stack trace:
#0 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(1738): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}  
[2015-03-09 19:02:43] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Http\Controllers\View' not found' in /home/simeon/dev/sbalo.bg/app/Http/Controllers/HomeController.php:11
Stack trace:
#0 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(1738): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}  
[2015-03-09 19:05:26] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Http\Controllers\View' not found' in /home/simeon/dev/sbalo.bg/app/Http/Controllers/HomeController.php:11
Stack trace:
#0 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(1738): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}  
[2015-03-09 19:05:27] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Http\Controllers\View' not found' in /home/simeon/dev/sbalo.bg/app/Http/Controllers/HomeController.php:11
Stack trace:
#0 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(1738): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}  
[2015-03-09 19:05:27] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Http\Controllers\View' not found' in /home/simeon/dev/sbalo.bg/app/Http/Controllers/HomeController.php:11
Stack trace:
#0 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(1738): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}  
[2015-03-09 19:05:27] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Http\Controllers\View' not found' in /home/simeon/dev/sbalo.bg/app/Http/Controllers/HomeController.php:11
Stack trace:
#0 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(1738): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}  
[2015-03-09 19:05:46] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Http\Controllers\View' not found' in /home/simeon/dev/sbalo.bg/app/Http/Controllers/HomeController.php:11
Stack trace:
#0 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(1738): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}  
[2015-03-09 19:09:01] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Http\Controllers\View' not found' in /home/simeon/dev/sbalo.bg/app/Http/Controllers/HomeController.php:11
Stack trace:
#0 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(1738): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}  
[2015-03-09 19:09:01] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Http\Controllers\View' not found' in /home/simeon/dev/sbalo.bg/app/Http/Controllers/HomeController.php:11
Stack trace:
#0 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(1738): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}  
[2015-03-09 19:09:01] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Http\Controllers\View' not found' in /home/simeon/dev/sbalo.bg/app/Http/Controllers/HomeController.php:11
Stack trace:
#0 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(1738): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}  
[2015-03-09 19:09:14] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Http\Controllers\View' not found' in /home/simeon/dev/sbalo.bg/app/Http/Controllers/HomeController.php:11
Stack trace:
#0 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(1738): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}  
[2015-03-09 19:09:17] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Http\Controllers\View' not found' in /home/simeon/dev/sbalo.bg/app/Http/Controllers/HomeController.php:11
Stack trace:
#0 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(1738): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}  
[2015-03-09 19:11:35] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Http\Controllers\View' not found' in /home/simeon/dev/sbalo.bg/app/Http/Controllers/HomeController.php:11
Stack trace:
#0 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(1738): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}  
[2015-03-09 19:11:36] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Http\Controllers\View' not found' in /home/simeon/dev/sbalo.bg/app/Http/Controllers/HomeController.php:11
Stack trace:
#0 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(1738): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}  
[2015-03-09 19:11:36] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Http\Controllers\View' not found' in /home/simeon/dev/sbalo.bg/app/Http/Controllers/HomeController.php:11
Stack trace:
#0 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(1738): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}  
[2015-03-09 19:11:36] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Http\Controllers\View' not found' in /home/simeon/dev/sbalo.bg/app/Http/Controllers/HomeController.php:11
Stack trace:
#0 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(1738): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}  
[2015-03-09 19:11:37] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Http\Controllers\View' not found' in /home/simeon/dev/sbalo.bg/app/Http/Controllers/HomeController.php:11
Stack trace:
#0 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(1738): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}  
[2015-03-09 19:11:37] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Http\Controllers\View' not found' in /home/simeon/dev/sbalo.bg/app/Http/Controllers/HomeController.php:11
Stack trace:
#0 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(1738): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}  
[2015-03-09 19:11:40] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Http\Controllers\View' not found' in /home/simeon/dev/sbalo.bg/app/Http/Controllers/HomeController.php:11
Stack trace:
#0 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(1738): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}  
[2015-03-09 20:33:35] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Http\Controllers\DB' not found' in /home/simeon/dev/sbalo.bg/app/Http/Controllers/MainController.php:11
Stack trace:
#0 /home/simeon/dev/sbalo.bg/storage/framework/compiled.php(1738): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}  
